# Generated by Django 3.0.3 on 2020-04-13 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='use_form',
            new_name='use_from',
        ),
    ]
